### PR TITLE
Update telnetd.c to add missing include

### PR DESCRIPTION
**Pull request by CTassisF**
`ripe-atlas-software-probe` will not compile in Alpine Linux 3.21 due to a missing include:

```
networking/telnetd.c: In function 'telnetd_main':
networking/telnetd.c:952:32: warning: declaration of 'tv' shadows a previous local [-Wshadow]
  952 |                 struct timeval tv;
      |                                ^~
networking/telnetd.c:809:24: note: shadowed declaration is here
  809 |         struct timeval tv;
      |                        ^~
networking/telnetd.c:1181:33: error: implicit declaration of function 'reboot' [-Wimplicit-function-declaration]
 1181 |                                 reboot(LINUX_REBOOT_CMD_RESTART);
      |                                 ^~~~~~
networking/telnetd.c:809:24: warning: unused variable 'tv' [-Wunused-variable]
  809 |         struct timeval tv;
      |                        ^~
make[2]: *** [scripts/Makefile.build:198: networking/telnetd.o] Error 1
make[1]: *** [Makefile:755: networking] Error 2
make: *** [Makefile:470: install-recursive] Error 1
```

This adds the missing `#include <sys/reboot.h>` to `telnetd.c`.

### CODE REVIEW

**Comment by wolfy1339** [comment]
This also affects Debian Trixie on GCC 14

**Comment by trixmoe** [comment]
Hi,

thanks for your PR.

It seems like a few people came across this issue, and it impacts multiple platforms.
With Debian 13's stable release slowly approaching, it makes _additional_ sense to merge this.

We've merged it internally and it will be part of the upcoming release.

--
Trix
RIPE NCC

**Comment by trixmoe** [comment]
Your contribution was merged in version 5110 in commit 09a06613c8483097a75601c4863b81300ed67f22.

--
Trix
RIPE NCC
